### PR TITLE
Added timestamp to log messages

### PR DESCRIPTION
**Pull request by jworcestBAH**
Small PR to add timestamps to log messages.

### CODE REVIEW

**Comment by bsweger** [comment]
@jworcestBAH done reviewing. From the perspective of someone who manually opens and reads local the error log, this looks fine. A question for the folks using LogStash....I'm not sure if there's some kind of front-end or utility that parses the log messages. If so, would we want the timestamp to be in the JSON, along with `error_log_message`, `error_log_type`, etc?

**Comment by jworcestBAH** [comment]
It's easy enough to have it be in the json as "error_timestamp", and that does seem better either way, so I'll go ahead and change that.

**Comment by jworcestBAH** [comment]
Okay pushed that change

**Comment by bsweger** [comment]
@jworcestBAH thanks, looks good!

**Pull request merged**
